baseurl: "https://vaibhaw.github.io/blog/"
title: Vaibhaw's Tech Musings
theme: ghostwriter
languageCode: en-us
copyright: Vaibhaw Singh Chandel
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: false
    respectDoNotTrack: false
    useSessionStorage: false

author:
  name: Vaibhaw Singh Chandel
  profile: "https://vaibhaw.github.io"

taxonomies:
  tag: tags

params:
  mainSections:
    - posts
    - notes
  logo: "logo.svg"
  intro: true
  headline: ""
  title: My encounters with programming, technology and gadgets
  # enabling description => ugly uppercase text
  # description: My encounters with programming, technology and gadgets
  github: "https://github.com/vaibhaw"
  gitlab: "https://gitlab.com/vaibhaw"
  linkedin: "https://linkedin.com/in/vaibhaw/"
  twitter: "https://twitter.com/vaibhaw"
  stackoverflow: "https://stackoverflow.com/users/875484/vaibhaw"
  facebook: "https://www.facebook.com/vaibhaw"
  lastfm: "https://www.last.fm/user/vaibhawchandel"
  atetracks: "https://8tracks.com/vaibhaw"
  email: "chandel.vaibhaw@gmail.com"
  opengraph: true
  shareTwitter: true
  shareFacebook: true
  shareGooglePlus: false
  shareLinkedIn: true
  dateFormat: "Jan 02, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Projects
      url: /projects/
      weight: 2
    - name: Blog
      url: /posts/
      weight: 3
    - name: Notes
      url: /notes/
      weight: 4
    - name: Tutorials
      url: /tutorials/
      weight: 5
    - name: Contact
      url: /page/contact/
      weight: 6
    - name: About
      url: /page/about/
      weight: 7
