baseurl = "https://vaibhawchandel.github.io/blog/"
title = "tech musings"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Vaibhaw Singh Chandel"
googleAnalytics = "XXX"
disqusShortname = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Vaibhaw Singh Chandel"
    profile = "https://google.com/+VaibhawSinghChandel"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    # headline = ""
    description = "My encounters with programming, technology and gadgets"
    github = "https://github.com/vaibhawchandel"
    gitlab = "https://gitlab.com/vaibhawchandel"
    linkedin = "https://linkedin.com/in/vaibhaw/"
    gplus = "https://google.com/+VaibhawSinghChandel"
    twitter = "https://twitter.com/vaibhaw"
    stackoverflow = "https://stackoverflow.com/users/875484/vaibhaw"
    email = "chandel.vaibhaw@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Monday, January 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4